In [53]:
pwd()

"c:\\Users\\Usuario\\CursoJulia\\Localizacion faltas\\localizadorjulia\\src"

In [54]:
using COMTRADE
using DataFrames



z1 = read_comtrade("../Oscilos/02.09.22 22.09.55.000.000")
VSCodeServer.vscodedisplay(z1.cfg.A) #Para ver los DataFrames
VSCodeServer.vscodedisplay(z1.cfg.D) #Para ver los DataFrames
VSCodeServer.vscodedisplay(z1.dat) #Para ver los DataFrames

In [55]:
fs=1200
Nh=10
N=2Nh+1
L=round(Integer,3N/6)

10

In [57]:
X= zeros(Float64,2Nh-L,L) # canal 3=Vc

X

10×10 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [60]:
for i=0:L-1
    v=z1.dat[(1+i):(L+i),3]
    X[:,i+1]=v
end
X

using LinearAlgebra

f=svd(X)

SVD{Float64, Float64, Matrix{Float64}}
U factor:
10×10 Matrix{Float64}:
 0.170208  -0.451252    0.287199   …  -0.177639     0.0307145   0.022399
 0.258726  -0.447964    0.325897       0.424873    -0.0495339  -0.0653756
 0.330823  -0.330506    0.194419      -0.591219    -0.0553376   0.025088
 0.381711  -0.109548   -0.0180336      0.534984    -0.0721241  -0.107375
 0.406299   0.093435   -0.240841      -0.350914    -0.0561192   0.0998829
 0.401518   0.172683   -0.364869   …  -0.0150931   -0.376297   -0.553333
 0.363511   0.0727773  -0.283772       0.1689      -0.0183254   0.78521
 0.328027   0.106574   -0.0957517      0.00634986   0.869295   -0.21918
 0.246722   0.406842    0.429117      -0.0151083   -0.274278    0.0399507
 0.148438   0.503727    0.55517        0.00386172   0.111135    0.0268584
singular values:
10-element Vector{Float64}:
 3095.4925090897345
 2112.9272491305783
 1367.6730229108082
 1115.6793371986305
  811.3689189263283
  772.5264608757374
  469.1706685373872
  355.62057

In [ ]:
X[1,1]